
[functions.migration-runner]
enabled = true
verify_jwt = true
import_map = "./functions/migration-runner/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/migration-runner/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/migration-runner/*.html" ]

[functions.lux-chat]
enabled = true
verify_jwt = false

[functions.lux-logic]
enabled = true
verify_jwt = false

[functions.preview-generator]
enabled = true
verify_jwt = false
